# Site
name: 'ThinhDA'
description: "This is a ThinhDA's blog"
logo: 'assets/images/page_icon.png'
favicon: 'assets/images/page_icon.png'
baseurl: 'https://thinhdanggroup.github.io'
# baseurl: ''
disqus: 'thinhda'
email: 'thinhdang206@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    thinhda:
      name:           ThinhDA
      site:           https://thinhdanggroup.github.io
      avatar:         /assets/images/avatar.png
      bio:            "Hi, I am Thinhda. If you want to know about me, please view my Linkedin profile at 'here'."
      email:          thinhda@gmail.com
      linkedin:       https://www.linkedin.com/in/thinh-dang/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: thinhda
      avatar: /assets/images/avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
style:  kjhealy

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
